---
jobs:
- name: build
  public: true
  plan:
  - aggregate:
    - get: pipeline
      resource: git-pipeline
      trigger: false
    - get: ybd
      resource: git-ybd
      trigger: false
    - get: definitions
      resource: git-definitions
      trigger: true
  - task: build-little-thing
    privileged: true
    config:
      platform: linux
      image: {{docker-hub-task-image}}
      inputs:
      - {name: pipeline}
      - {name: ybd}
      - {name: definitions, path: .}
      run:
        path: ./pipeline/scripts/build_ybd.sh
        args: []


resources:
- name: git-pipeline
  type: git
  source:
    uri: https://github.com/drnic/ydb-pipeline-demo.git
    branch: master
- name: git-ybd
  type: git
  source:
    uri: https://github.com/devcurmudgeon/ybd.git
    branch: master
- name: git-definitions
  type: git
  source:
    uri: git://git.baserock.org/baserock/baserock/definitions.git
    branch: master
